import { Geist, Geist_Mono, Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Next Crash",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="p-6">
      <body className={inter.className}>
        <nav>
          <ul className="flex gap-5">  
            <li><Link href="/">Home</Link></li>
            <li><Link href="/blogs">Blog</Link></li>
            <li><Link href="/about">About</Link></li>
            <li><Link href="/posts">Post</Link></li>
          </ul>
        </nav>
        <hr />

        {children}
      </body>
    </html>
  );
}
